name: My First workflow
on: [push]
jobs:
  my-run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
      - name: my echo
        run: echo "Sunny  Hell World "
      - name: Multiple Commands
        run: | 
          node -v
          npm -v