name: Check my status - b
on: [push]

jobs:
  my-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Step 2
        id: my-step-2
        continue-on-error: true     # with this "continue-on-error" even if this step fails we can say that this workflow should not fail
        run: exit 1                           
      - name: Runs only if "Step 2" failes    
        if: failure() && steps.my-step-2.conclusion == 'failure'  
        run: echo 'Step 2 has failed'        
      - name: Runs only Failure
        if: failure() 
        run: echo 'When we get and Failure'            
      - name: Runs on Success
        if: success()    
        run: echo 'Run on Success'  
      - name: Always run
        if: always()   
        run: echo 'It will Run Always'
      - name: Runs when Cancelled
        if: cancelled()
        run: echo 'Runs on Cancelled'
  my-job-2:
    runs-on: ubuntu-latest
    needs: my-job-1
    if: failure()
    steps: 
      - run: echo 'Job 2'