name: Check my status
on: [push]

jobs:
  my-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs on Failure
        if: failure()  #  it means if "failure" then it return "true"
        run: echo 'Runs only on failure'
      - name: Runs on Success
        if: success()   # success is the default behaviour, 
        run: echo 'Run on Success'  
      - name: Always run
        if: always()     # it return true, It is always going to run, either "success" or "failure"
        run: echo 'It will Run Always'
      - name: Runs when Cancelled
        if: cancelled()
        run: echo 'Runs on Cancelled'
  my-job-2:
    runs-on: ubuntu-latest
    needs: my-job-1
    if: failure()
    steps: 
      - run: echo 'Job 2'