name: Variables and Secrets
on: [push]

jobs: 
  my-log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}             # accessing a Orgination "Variable"
    environment: "production"
    env: 
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
      ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true 
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "I ran"
      - name: Log Vars
        run: |
          echo JOBS_RUNNER:      '${{ vars.JOBS_RUNNER }}'  
          echo "ENV_LEVEL_VAR:    $ENV_LEVEL_VAR"
          echo "REPO_LEVEL_VAR:   $REPO_LEVEL_VAR"
          echo "ORG_LEVEL_VAR:    $ORG_LEVEL_VAR"