name: Pull request comment
on:
  pull_request_target:
    types: [opened]
jobs:
  my-pr-comment:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
#    permissions: read-all   # It means it GITHUB_TOKEN has read permission for all type
#    permissions: write-all  # It means GITHUB_TOKEN has write permission for all types
#    permissions: {}         # It means GITHUB_TOKEN has no permission to do anything
    steps:
      - name: Comment on New PRs
        uses: actions/github-script@v6
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: | 
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: ' Thanks for contrihuting',
            });


