name: Matrix
on: [push]

jobs: 
  my-node-version:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [14,15,16]  # like this we have in our workfow another node language version without defining saperatelly
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: node -v