name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: my- Setting a error message
        run: echo "::error::my Missing semicolon"
      - name: Setting an error message with params
        run: echo "::error title:Error title, file=app.js, line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Setting an debug message with params
        run: echo "::debug title:Debug title, file=app.js, line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"        
      - name: Setting an warrning message with params
        run: echo "::warning title:Warning title, file=app.js, line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"        
      - name: Setting an notic message with params
        run: echo "::notic title:Notice title, file=app.js, line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Group of logs
        run: |
          echo "::group:: Ny group title"
          echo "Inside group"
          echo "::endgroup::"
      - name: Masking a value 
        run: echo "::add-mask::My Secret String"
      - name: Echo a secret 
        run: echo "My Secret String"  