name: Matrix Field C
on: [push]


#------- ORIGINAL --------#
# X {os: ubuntu-latest, node-version: 14, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 15, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 16, is-ubuntu: true, experimental: true}
# {os: windows-latest, node-version: 14, experimental: false}
# {os: windows-latest, node-version: 15, experimental: false}
# {os: windows-latest, node-version: 16, experimental: false}
# {os: macos-latest, node-version: 15}
# {os: ubuntu-latest, node-version: 17 }

jobs: 
  my-node-versio:
    continue-on-error: ${{ matrix.experimental == true }}
    strategy: 
      matrix: 
        os: [ubuntu-latest, windows-latest]
        node-version: [14,15,16]  
        include:
          - os: ubuntu-latest
            is-ubunut: ture
          - os: macos-latest
            node-version: 15
          - experimental: false  
          - os: ubunut-latest
            node-version: 16
            experimental: true 
          - os: ubuntu-latest
            node-version: 17
        exclude: 
          - os: ubuntu-latest 
            node-version: 14
      max-parallel: 3       
      fail-fast: true   
    runs-on: ${{ matrix.os }} 
    steps:
      - if: matrix.experimental == true
        run: exit 1
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: node -v