name: Matrix Field D
on:
  workflow_dispatch:
    inputs:
      os: 
        description: Operating System
        default: "windows-latest,ubuntu-latest"
        type: string
      node-version:
        description: Node version
        default: "14,15,16"
        type: string

jobs:
  my-prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: echo "aaa=value" >> $GITHUB_OUTPUT
        id: my-step-1 
      - run: echo "aaa=value 2" >> $GITHUB_OUTPUT
        id: my-step-2
      - run: |
          echo '${{ steps.my-step-1.outputs.aaa }}'  
          echo '${{ steps.my-step-2.outputs.aaa }}'                     
  my-node-versio:
    strategy: 
      matrix: 
        os: [ubuntu-latest, windows-latest]
        node-version: [14,15,16]
    runs-on: ${{ matrix.os }} 
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: node -v