name: Matrix Field D
on:
  workflow_dispatch:
    inputs:
      os: 
        description: Operating System
        default: "windows-latest,ubuntu-latest"
        type: string
      node-version:
        description: Node version
        default: "14,15,16"
        type: string

jobs:
  aa:                   # A -  this is the job name, with this name we can get this whole job output below
    runs-on: ubuntu-latest
    outputs: 
      my-matrix-arrays: ${{ steps.my-matrix-array.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: my-matrix-array
        with: 
          script: "return {os: context.payload.inputs['os'].split(','), 'node-version': context.payload.inputs['node-version'].split(',') }"
          result-encoding: json
      - run: echo '${{ steps.my-matrix-array.outputs.result }}'    
      - run: echo "a1=value" >> $GITHUB_OUTPUT
        id: my-step-1 
      - run: echo "b1=value 2" >> $GITHUB_OUTPUT
        id: my-step-2                    # with the help of this "id" we are able to print the result of this step below.
      - run: |
          echo '${{ steps.my-step-1.outputs.a1 }}'  
          echo '${{ steps.my-step-2.outputs.b1 }}'                     
  bb:
    needs: aa            # B -  "needs" with this field name we are making the whole output of above step for us
    strategy:            #      as we are putting the name of the above step here        
      matrix: 
        os: ${{ fromJson(needs.aa.outputs.my-matrix-arrays).os }}         # c - here we are using theoutput of the "aa" whole step
        node-version: ${{ fromJson(needs.aa.outputs.my-matrix-arrays).node-version }}
    runs-on: ${{ matrix.os }} 
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: node -v