name: Calling Resuable Workflow
on:
 workflow_dispatch:
   inputs:
     name: 
       description: "Input description"
       type: string
       default: "Ali"
       required: false 

jobs: 
  calling-a-resuable-wf:
    uses: my-workflow-organization/my-resuable-workflow/.github/workflows/my-resuable.yaml@main  # we can put a tag or commit-id, branch name
    with: 
      name: ${{ inputs.name }}
    secrets: 
      access-token: ${{ secrets.MY_ACCESS_TOKEN }}
        