name: Calling Resuable Workflow B
on:
 workflow_dispatch:
   inputs:
     name: 
       description: "Input description"
       type: string
       default: "Ali"
       required: false 

jobs: 
  calling-a-resuable-wf:
    uses: my-workflow-organization/my-resuable-workflow/.github/workflows/my-resuable.yaml@main  # we can put a tag or commit-id, branch name
    with: 
      name: ${{ inputs.name }}
    secrets: 
      my-access-token: ${{ secrets.MY_ACCESS_TOKEN }}
  calling-a-resuable-wf-in-the-same-repo:
    uses: ./.github/workflows/25-a-resuable-wf-seperate.yaml
    secrets: inherit
#      access-token: ${{ secrets.MY_ACCESS_TOKEN }}
  using-reusable-wg-output:
    runs-on: ubuntu-latest
    needs: calling-a-resuable-wf-in-the-same-repo
    steps:
      - run: echo ${{ needs.calling-a-resuable-wf-in-the-same-repo.outputs.dateCC }}