name: Docker Workflow
on:
  workflow_dispatch
jobs:
  my-docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:20.3-alpine3.17
      # credentials:
      #   username: 
      #   password:
      env: 
        MY_API_URL: some-url.com
      ports:
        - 80
      # volumes:
      #   - vol_name:/path/in/container
      #   - path/to/container
      #   - path/in/host:/path/in/container   
      # options: --cpus 1
    steps:
      - name: Log Node & OS Versions
        run: | 
          node -v   
          cat /etc/os-release
      - name: Log env variable
        run: echo  MY_API_URL  

      