name: My Manually Trigger
on:
  workflow_dispatch:
    inputs:
      sunny-string:
        description: A String input
        type: string
        required: true
        default: "Default value"
      sunny-number:
        description: A number inpug
        default: 4
        type: number 
      option: 
        description: "An Options Input"
        required: true 
        default: "Option 3"
        type: choice
        options: 
          - My-Option 1
          - MY-Option 2
          - My-Option 3
      boolean: 
        description: A boolean option
        required: false
        type: boolean
      my-environment:
        description:  "MY Environment"
        type: environment
        required: true  
jobs:
  my-log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo "String: ${{ inputs.sunny-string }}"
          echo "String: ${{ inputs.sunny-number }}"
          echo "String: ${{ inputs.option }}"
          echo "String: ${{ inputs.boolean }}"
          echo "String: ${{ inputs.my-environment }}"